#!/bin/csh
#PBS -S /bin/csh
#PBS -N gitm.hiwind18

# set the number of CPU-s by changing select: nProc = select*mpiprocs
# ncpus should be fixed to 8 (or 12) because there are 8 (or 12) cores on 
# each node. The faster nodes mean faster execution, but also more charged
# to the account. 

#PBS -lselect=20:ncpus=20:model=ivy
#PBS -l walltime=48:00:00
#PBS -W group_list=s2516
#PBS -j oe
#PBS -m eb

cd $PBS_O_WORKDIR

#module load comp-intel/2015.0.090 mpi-sgi/mpt.2.14r19
module load comp-intel/2016.2.181 mpi-hpe/mpt

#rm -f UAM.in ; ln -s UAM.in.Start UAM.in
rm -f UAM.in ; ln -s UAM.in.Restart UAM.in
mpiexec -np 400 GITM.exe > log.restart

